### PR TITLE
[Tests] add fixture with remapped folder

### PR DESCRIPTION
**Pull request by bgotink**
Adds a fixture with a remapped folder, where the remapped name also exists. The example is a bit contrived, but it does showcase two bugs:

1. The `/mapped/` export is mapped onto `/unmapped/`, making it impossible to require any of the files in the actual `mapped` folder. The `mapped/index.js` file does show up in the result. This is linked to #77
2. The `"tree"` doesn't show the mapping

In other words, I'd expect

   ```diff
    "tree": {
      "ex-folder-mapped": {
        "unmapped": {
          "index.js": [
   +        "ex-folder-mapped/mapped",
   +        "ex-folder-mapped/mapped/",
   +        "ex-folder-mapped/mapped/index",
   +        "ex-folder-mapped/mapped/index.js",
            "ex-folder-mapped/unmapped",
            "ex-folder-mapped/unmapped/",
            "ex-folder-mapped/unmapped/index",
            "ex-folder-mapped/unmapped/index.js"
          ]
        },
        "index.js": [
          "ex-folder-mapped",
          "ex-folder-mapped/index",
          "ex-folder-mapped/index.js"
        ],
        "package.json": [
          "ex-folder-mapped/package",
          "ex-folder-mapped/package.json"
   -    ],
   -    "mapped": {
   -      "index.js": [
   -        "ex-folder-mapped/mapped",
   -        "ex-folder-mapped/mapped/",
   -        "ex-folder-mapped/mapped/index",
   -        "ex-folder-mapped/mapped/index.js"
   -      ]
   -    }
   +    ]
      }
    },
   ```

### CODE REVIEW

**Comment by ljharb** [comment]
Can we add another commit that corrects the fixtures (for preact too) to what they should be? then i can fix things to make them pass.

**Comment by bgotink** [comment]
Done!

I've noticed a third bug: conditions aren't supported in `/` exports. I've added a fixture for that as well.
The expected.json files for that fixture are completely handwritten, so I wouldn't be surprised if I'd made some errors there.

Result:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at processExportsEntry (/path/to/list-exports/packages/list-exports/index.js:371:26)
    at Array.forEach (<anonymous>)
    at listExports (/path/to/list-exports/packages/list-exports/index.js:394:30)
    at async Test.<anonymous> (/path/to/list-exports/packages/tests/index.js:63:20) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

```
$ node
Welcome to Node.js v14.12.0.
Type ".help" for more information.
> require.resolve('conditions-in-folder')
'/path/to/node_modules/conditions-in-folder/cjs/index.js'
> require.resolve('conditions-in-folder/utils')
'/path/to/node_modules/conditions-in-folder/cjs/utils.js'
> 
```

**Comment by ljharb** [comment]
I updated the fixtures; a few slash specifiers should continue to work (unless node itself contradicts me; hopefully the tests verify that).

I'll take a look at the fix this week.

**Comment by ljharb** [comment]
To fix this, I'm going to attempt to rewrite the entire algorithm from scratch, and see if that ends up with something less recursive and gross and broken :-) I'll hopefully have an update within the week.

**Comment by bgotink** [comment]
@ljharb Thanks!
I'd be happy to help if there's anything I can do.

**Comment by ljharb** [comment]
As an update: I've rewritten the entire package, and had everything passing, and then i incorporated your test cases so i'd be able to rebase this PR and land it, and now i'm having trouble again :-) i'll hopefully be able to finish up soon.

**Comment by ljharb** [comment]
@bgotink :-( i really wish you hadn't deleted the fork, this is still very much on my roadmap.

**Comment by bgotink** [comment]
@ljharb My sincere apologies, I forgot to check if there were open PRs before deleting the fork.
I've reopened the PR as #81.

**Pull request closed without merging**
